import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Classic gold chain with flower pendant",
    subCategory: "Chains",  
    weight: 6.25,
    categoryName: "Gold",
    imageURL: "../../assests/chains_gold_1.jpg",
  },
  {
    _id: uuid(),
    title: "Elegant gold chain with sun pendant",
    subCategory: "Chains",
    weight: 8.17,
    categoryName: "Gold",
    imageURL: "../../assests/chains_gold_2.jpg",
  },
  {
    _id: uuid(),
    title: "Double classic gold chain with star pendant",
    subCategory: "Chains",
    weight: 12,
    categoryName: "Gold",
    imageURL: "../../assests/chains_gold_3.jpg",
  },
  {
    _id: uuid(),
    title: "Flower shaped stone silver chain",
    subCategory: "Chains",  
      weight: 11.25,
    categoryName: "Silver",
    imageURL: "../../assests/chains_silver_1.jpg",
  },
  {
    _id: uuid(),
    title: "Silver diamond pendant chain",
    subCategory: "Chains",
    weight: 12.17,
    categoryName: "Silver",
    imageURL: "../../assests/chains_silver_2.jpg",
  },
  {
    _id: uuid(),
    title: "Silver beads pendant chain",
    subCategory: "Chains",
    weight: 7.15,
    categoryName: "Silver",
    imageURL: "../../assests/chains_silver_3.jpg",
  },
  {
    _id: uuid(),
    title: "Dual colored loop earring",
    subCategory: "Earrings",  
      weight: 2.25,
    categoryName: "Gold",
    imageURL: "../../assests/earring_gold_1.jpg",
  },
  {
    _id: uuid(),
    title: "Three layered semi-hoop earring",
    subCategory: "Earrings",
    weight: 3,
    categoryName: "Gold",
    imageURL: "../../assests/earring_gold_2.jpg",
  },
  {
    _id: uuid(),
    title: "Semi-hoop with U stones drop earrings",
    subCategory: "Earrings",
    weight: 6,
    categoryName: "Gold",
    imageURL: "../../assests/earring_gold_3.jpg",
  },
  {
    _id: uuid(),
    title: "Ruby drop hoop earrings",
    subCategory: "Earrings",
    weight: 4.35,
    categoryName: "Gold",
    imageURL: "../../assests/earring_gold_4.jpg",
  },
  {
    _id: uuid(),
    title: "Single stone silver earrings",
    subCategory: "Earrings",  
      weight: 3,
    categoryName: "Silver",
    imageURL: "../../assests/earring_silver_1.jpg",
  },
  {
    _id: uuid(),
    title: "Color stone silver earrings (Set of 4)",
    subCategory: "Earrings",
    weight: 12.5,
    categoryName: "Silver",
    imageURL: "../../assests/earring_silver_2.jpg",
  },
  {
    _id: uuid(),
    title: "Sapphire silver earring",
    subCategory: "Earrings",
    weight: 4,
    categoryName: "Silver",
    imageURL: "../../assests/earring_silver_3.jpg",
  },{
    _id: uuid(),
    title: "Three layered gold ring",
    subCategory: "Ring",  
      weight: 3.5,
    categoryName: "Gold",
    imageURL: "../../assests/ring_gold_1.jpg",
  },
  {
    _id: uuid(),
    title: "Elegant gold ring",
    subCategory: "Ring",
    weight: 2.65,
    categoryName: "Gold",
    imageURL: "../../assests/ring_gold_2.jpg",
  },
  {
    _id: uuid(),
    title: "Traditional cut modeled ring",
    subCategory: "Ring",
    weight: 4,
    categoryName: "Gold",
    imageURL: "../../assests/ring_gold_3.jpg",
  },
  {
    _id: uuid(),
    title: "Dazzling silver ring",
    subCategory: "Ring",  
      weight: 4.65,
    categoryName: "Silver",
    imageURL: "../../assests/ring_silver_1.jpg",
    },
  {
    _id: uuid(),
    title: "Lovely floral ring",
    subCategory: "Ring",
    weight: 4,
    categoryName: "Silver",
    imageURL: "../../assests/ring_silver_2.jpg",
  },
  {
    _id: uuid(),
    title: "Magnificient three stone ring",
    subCategory: "Ring",
    weight: 3.95,
    categoryName: "Silver",
    imageURL: "../../assests/ring_silver_4.jpg",
  },
];
